[package]
name = "web_api"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.8.6" }
axum-extra = { version = "0.10.3", features = ["typed-header"] }
tokio = { version = "1.47.1", features = ["full"] }
tower-http = { version = "0.6.6", features = ["cors"] }
jsonwebtoken = { version = "10.0.0" ,features = ["rust_crypto"]}
validator = { version = "0.20.0", features = ["derive"] }

sea-orm = { version = "1.1.17", features = ["sqlx-postgres", "runtime-tokio", "macros"] }
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
serde_urlencoded = "0.7.1"

dotenvy = "0.15.7"
anyhow = "1.0.100"
thiserror = "2.0.17"
chrono = { version = "0.4.42", default-features = false, features = ["clock", "serde"] }

[profile.release]
lto = true
strip = true
codegen-units = 1
panic = "abort"
opt-level = 3

[lints.rust]
unused_variables = "allow"
