[package]
name = "web_api"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = ["headers"] }
tokio = { version = "1.34.0", features = ["full"] }
tower-http = { version = "=0.4.4", features = ["cors"] }
jsonwebtoken = "9.1.0"
validator = { version = "0.16.1", features = ["derive"] }

sea-orm = { version = "0.12.7", features = ["sqlx-postgres", "runtime-tokio-native-tls", "macros"] }
serde_json = "1.0.108"
serde = { version = "1.0.193", features = ["derive"] }
serde_urlencoded = "0.7.1"

dotenvy = "0.15.7"
anyhow = "1.0.75"
thiserror = "1.0.50"
chrono = "0.4.31"

[profile.release]
lto = true
strip = true
codegen-units = 1
