[package]
name = "web_api"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.8.9", default-features = false, features = ["http1", "json", "query", "tokio", "tower-log", "tracing"] }
axum-extra = { version = "0.12.6", features = ["typed-header"] }
tokio = { version = "1.53.1", features = ["macros", "net", "rt-multi-thread"] }
tower-http = { version = "0.7.1", features = ["cors"] }
jsonwebtoken = { version = "11.0.0", default-features = false, features = ["rust_crypto"] }
validator = { version = "0.21.0", features = ["derive"] }

sea-orm = { version = "2.0.2", default-features = false, features = ["sqlx-postgres", "runtime-tokio", "macros", "with-chrono"] }
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }
serde_urlencoded = "0.7.1"

dotenvy = "0.15.7"
anyhow = "1.0.104"
thiserror = "2.0.20"
chrono = { version = "0.4.45", default-features = false, features = ["clock", "serde"] }

[profile.release]
lto = true
strip = true
